### ISSUE TITLE
Add new page for copy-paste results

### ISSUE THREAD

**Issue by phaldan** [htwg-cloud-application-development/frontend#28]
Results should be grouped by course.

**Comment by T1m1** [comment]
![image](https://cloud.githubusercontent.com/assets/5616884/16245362/c1f5cf62-3800-11e6-836c-c3158b8a2141.png)
![image](https://cloud.githubusercontent.com/assets/5616884/16245374/ce57d494-3800-11e6-8266-f55837bf92f9.png)

**Comment by phaldan** [comment]
Awesome! Now I can start to create the page
